services:
  inn_app:
    build: ./
    image: ryzeon/inn_app:latest
    mem_limit: 512m
    ports:
      - "8045:8045"
    environment:
      DB_URL: jdbc:mysql://inn_app_mysql:3306/inncontrol_backend?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: securepassword123
    restart: always
    depends_on:
      inn_app_mysql:
        condition: service_healthy
  inn_app_mysql:
    image: 'mysql:latest'
    ports:
      - "3309:3309"
    environment:
      MYSQL_ROOT_PASSWORD: securepassword123
      MYSQL_PASSWORD: securepassword123
      MYSQL_DATABASE: inncontrol_backend
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10